version: "3.8"

services:
  # SQLite Database Container
  sqlite-db:
    image: alpine:latest
    container_name: sqlite-database
    volumes:
      - db-data:/shared
    command: sh -c "
      apk add --no-cache sqlite &&
      mkdir -p /shared &&
      cd /shared &&
      echo 'Creating SQLite database...' &&
      sqlite3 notes.db 'CREATE TABLE IF NOT EXISTS notes (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      author TEXT NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
      );' &&
      echo 'Database created successfully!' &&
      tail -f /dev/null"
    networks:
      - note-network
    healthcheck:
      test: ["CMD", "test", "-f", "/shared/notes.db"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Frontend App Container
  noteapp:
    build: .
    container_name: simple-note-app
    ports:
      - "5000:5000"
    environment:
      - DB_TYPE=sqlite
      - DB_PATH=/shared/notes.db
      - FLASK_PORT=5000
    volumes:
      - db-data:/shared
    depends_on:
      sqlite-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - note-network

# Create a network for services communication
networks:
  note-network:
    driver: bridge

# Create a shared volume for database
volumes:
  db-data:
    driver: local
