---
# Common Role - System Setup for Amazon Linux
# Handles basic system configuration and package installation

- name: Update system packages
  yum:
    name: "*"
    state: latest
    update_cache: true
  tags: packages

- name: Install essential packages for Amazon Linux
  yum:
    name:
      - python3
      - python3-pip
      - git
      - wget
      - curl
      - unzip
      - sqlite
      - httpd
      - httpd-tools
    state: present
  tags: packages

- name: Install Python packages
  pip:
    name:
      - flask
      - gunicorn
    executable: pip3
  tags: python

- name: Create application user
  user:
    name: "{{ app_user }}"
    system: true
    shell: /bin/bash
    home: "{{ app_dir }}"
    create_home: false
  tags: users

- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  loop:
    - "{{ app_dir }}"
    - "{{ app_dir }}/app"
    - "{{ app_dir }}/database"
    - "{{ app_dir }}/backups"
    - "{{ app_dir }}/logs"
  tags: directories

- name: Configure firewall for HTTP
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
  notify: restart firewalld
  tags: firewall

- name: Configure firewall for SSH
  firewalld:
    service: ssh
    permanent: true
    state: enabled
    immediate: true
  notify: restart firewalld
  tags: firewall

- name: Start and enable Apache HTTP server
  systemd:
    name: httpd
    state: started
    enabled: true
  tags: services 