---
# Common Role Handlers

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted

- name: restart httpd
  systemd:
    name: httpd
    state: restarted

- name: reload httpd
  systemd:
    name: httpd
    state: reloaded 