---
# Database Role - SQLite Setup
# Creates and configures SQLite database for notes

- name: Ensure SQLite is installed
  yum:
    name: sqlite
    state: present
  tags: sqlite

- name: Create database directory
  file:
    path: "{{ app_dir }}/database"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  tags: database

- name: Copy database initialization script
  template:
    src: init_db.sql.j2
    dest: "{{ app_dir }}/database/init_db.sql"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0644'
  tags: database

- name: Initialize SQLite database
  shell: |
    sqlite3 {{ sqlite_db_path }} < {{ app_dir }}/database/init_db.sql
  args:
    creates: "{{ sqlite_db_path }}"
  become_user: "{{ app_user }}"
  tags: database

- name: Set correct permissions on database file
  file:
    path: "{{ sqlite_db_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0664'
  tags: database

- name: Create database backup directory
  file:
    path: "{{ app_dir }}/backups/database"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  tags: backup

- name: Verify database structure
  shell: sqlite3 {{ sqlite_db_path }} ".schema notes"
  become_user: "{{ app_user }}"
  register: db_schema
  changed_when: false
  tags: verify

- name: Display database schema
  debug:
    msg: "Database schema created: {{ db_schema.stdout }}"
  tags: verify 