---
# Default variables for noteapp role
# These can be overridden in group_vars, host_vars, or playbook vars

# Application Configuration
app_name: "note-taking-app"
app_dir: "/opt/note_app"
app_user: "ec2-user"
app_group: "ec2-user"

# Repository Configuration
repo_url: "https://github.com/AmrDabour/ansible-project.git"
repo_branch: "master"

# Application Ports
app_port: 5000
fallback_port: 8080

# Python Configuration
python_executable: "/usr/bin/python3"
pip_executable: "pip3"

# Database Configuration
database_file: "notes.db"
database_setup_script: "setup_database.sh"

# Service Configuration
service_name: "noteapp"
service_description: "Note Taking Web App"

# Security Configuration
firewall_ports:
  - "5000/tcp"
  - "8080/tcp"

# Environment Configuration
app_environment: "production"

# Package List
required_packages:
  - git
  - python3
  - python3-pip
  - sqlite

# File Permissions
directory_mode: "0755"
script_mode: "0755"

# Application Environment
flask_env: "production"
flask_debug: false

# Deployment Settings
force_clone: true
restart_service: true
enable_service: true

# Backup Configuration
backup_enabled: false
backup_dir: "/opt/backups/note_app"

# Monitoring Configuration
monitoring_enabled: false
log_level: "info"
