---
- name: Deploy Simple Note App from GitHub
  hosts: webservers
  become: yes
  gather_facts: yes
  
  vars:
    app_name: "simple_note_app"
    app_dir: "/opt/{{ app_name }}"
    app_user: "ec2-user"
    app_port: 5000
    repo_url: "https://github.com/AmrDabour/ansible-project.git"
    repo_branch: "master"
    
  roles:
    - noteapp
