---
- name: Remove Note-Taking Web App using Ansible Role
  hosts: webservers
  become: true
  
  tasks:
    - name: Include cleanup tasks from noteapp role
      include_tasks: roles/noteapp/tasks/cleanup.yml
      vars_files:
        - roles/noteapp/vars/main.yml
