---
- name: Verify Server is Clean (Plain State)
  hosts: webservers
  become: yes
  vars_files:
    - vars.yml
    
  tasks:
    - name: Check if application directory exists
      stat:
        path: "{{ app_dir }}"
      register: app_dir_check
      
    - name: Check if service file exists
      stat:
        path: "/etc/systemd/system/{{ service_name }}.service"
      register: service_file_check
      
    - name: Check if service is running
      systemd:
        name: "{{ service_name }}"
      register: service_status
      ignore_errors: yes
      
    - name: Check firewall status for app ports
      shell: firewall-cmd --list-ports
      register: firewall_status
      ignore_errors: yes
      
    - name: Display server cleanliness status
      debug:
        msg: |
          === SERVER CLEANLINESS CHECK ===
          
          Application Directory ({{ app_dir }}): {{ 'EXISTS (not clean!)' if app_dir_check.stat.exists else 'REMOVED (clean)' }}
          
          Service File: {{ 'EXISTS (not clean!)' if service_file_check.stat.exists else 'REMOVED (clean)' }}
          
          Service Status: {{ service_status.status.ActiveState | default('INACTIVE (clean)') }}
          
          Firewall Ports: {{ firewall_status.stdout | default('No ports listed') }}
          
          Overall Status: {{ 'SERVER IS CLEAN ✓' if not (app_dir_check.stat.exists or service_file_check.stat.exists) else 'SERVER NEEDS MORE CLEANUP ✗' }}
          
          The server is {{ 'ready for new deployments' if not (app_dir_check.stat.exists or service_file_check.stat.exists) else 'not completely clean yet' }}.
